from abc import ABC, abstractmethod
from typing import Dict, Any
from app.config import get_settings
from app.models import Transaction, Document, DocumentType
from sqlalchemy.orm import Session
import os
import logging
from datetime import datetime

settings = get_settings()
logger = logging.getLogger(__name__)


class DocumentGenerator(ABC):
    """Abstract document generator."""
    
    @abstractmethod
    def generate(self, transaction: Transaction, doc_type: DocumentType) -> str:
        """Generate document and return file path."""
        pass


class PDFDocumentGenerator(DocumentGenerator):
    """Generate PDF documents using fpdf2."""
    
    def __init__(self):
        self.output_dir = settings.documents_path
        os.makedirs(self.output_dir, exist_ok=True)
    
    def generate(self, transaction: Transaction, doc_type: DocumentType) -> str:
        from fpdf import FPDF
        
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 16)
        
        # Title
        titles = {
            DocumentType.E_INVOICE: "E-INVOICE",
            DocumentType.E_WAY_BILL: "E-WAY BILL",
            DocumentType.DISPATCH_NOTE: "DISPATCH NOTE",
            DocumentType.PAYMENT_RECORD: "PAYMENT SETTLEMENT RECORD"
        }
        pdf.cell(0, 10, titles.get(doc_type, "DOCUMENT"), ln=True, align="C")
        pdf.ln(5)
        
        # Transaction details
        pdf.set_font("Helvetica", "", 10)
        bale = transaction.bale
        
        details = [
            ("Transaction ID", transaction.transaction_id),
            ("Bale ID", bale.bale_id),
            ("Certificate ID", bale.certificate_id),
            ("Farmer ID", bale.farmer_id),
            ("Crop Type", bale.crop_type),
            ("Residue Type", bale.residue_type),
            ("Declared Weight (kg)", str(bale.declared_weight)),
            ("Verified Weight (kg)", str(transaction.verified_weight)),
            ("Reference Rate (?/kg)", str(transaction.reference_rate)),
            ("Total Amount (?)", str(transaction.total_amount)),
            ("Hub ID", bale.hub_id),
            ("Pool ID", bale.pool_id or "N/A"),
            ("Date", transaction.created_at.strftime("%Y-%m-%d %H:%M:%S")),
        ]
        
        if doc_type == DocumentType.E_WAY_BILL:
            details.extend([
                ("From", f"Hub {bale.hub_id}"),
                ("To", "Buyer Location"),
                ("Distance (km)", "TBD"),
            ])
        
        if doc_type == DocumentType.DISPATCH_NOTE:
            details.extend([
                ("Dispatched From", f"Hub {bale.hub_id}"),
                ("Vehicle No", "TBD"),
                ("Driver", "TBD"),
            ])
        
        if doc_type == DocumentType.PAYMENT_RECORD:
            payment = transaction.payment
            if payment:
                details.extend([
                    ("Payment ID", payment.payment_id),
                    ("Payment Provider", payment.provider),
                    ("Payment Status", payment.status.value),
                ])
        
        for label, value in details:
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(60, 8, f"{label}:")
            pdf.set_font("Helvetica", "", 10)
            pdf.cell(0, 8, value, ln=True)
        
        pdf.ln(10)
        pdf.set_font("Helvetica", "I", 8)
        pdf.cell(0, 5, f"Generated by AgriLoop on {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC", ln=True, align="C")
        pdf.cell(0, 5, f"Mode: {'DEMO' if settings.demo_mode else 'PRODUCTION'}", ln=True, align="C")
        
        # Save
        filename = f"{transaction.transaction_id}_{doc_type.value.lower()}.pdf"
        filepath = os.path.join(self.output_dir, filename)
        pdf.output(filepath)
        
        return filepath


class DocumentService:
    def __init__(self, db: Session):
        self.db = db
        self.generator = PDFDocumentGenerator()
    
    def generate_all_documents(self, transaction: Transaction) -> list:
        """Generate all required documents for a transaction."""
        doc_types = [
            DocumentType.E_INVOICE,
            DocumentType.E_WAY_BILL,
            DocumentType.DISPATCH_NOTE,
            DocumentType.PAYMENT_RECORD
        ]
        
        generated = []
        for doc_type in doc_types:
            # Check if already exists
            existing = self.db.query(Document).filter(
                Document.transaction_id == transaction.id,
                Document.document_type == doc_type
            ).first()
            
            if existing:
                logger.info(f"Document {doc_type.value} already exists for transaction {transaction.transaction_id}")
                generated.append(existing)
                continue
            
            # Generate document
            filepath = self.generator.generate(transaction, doc_type)
            
            # Create document record
            document = Document(
                document_id=f"DOC-{transaction.transaction_id}-{doc_type.value[:3].upper()}",
                transaction_id=transaction.id,
                document_type=doc_type,
                url=filepath,
                status="GENERATED"
            )
            
            self.db.add(document)
            generated.append(document)
        
        self.db.commit()
        for doc in generated:
            self.db.refresh(doc)
        
        return generated
    
    def get_documents(self, transaction_id: str) -> list:
        """Get all documents for a transaction."""
        transaction = self.db.query(Transaction).filter(
            Transaction.transaction_id == transaction_id
        ).first()
        
        if not transaction:
            return []
        
        return self.db.query(Document).filter(
            Document.transaction_id == transaction.id
        ).all()
